### ISSUE TITLE
Make a Bower Package

### ISSUE THREAD

**Issue by jpuffer** [kirkjerk/lowLagAudio#6]
Would it be possible to make this into a [Bower](http://bower.io/) package?

**Comment by honkskillet** [comment]
+1

**Comment by honkskillet** [comment]
I just put in a pull request with a bower.son file I created.  There is currently

**Comment by honkskillet** [comment]
Thanks for merging.  I just changed the bower registry so that now it points towards this repo and not my fork.  cheers
(Probably OK to close this issue.)

**Comment by kirkjerk** [comment]
Thanks for the support! I tend to keep things simplistic enough that bower isn't super helpful, but I should get more into the flow of it.

**Comment by fgrond** [comment]
Hi Kirkjerk, I'm using lowlag for a while to trigger sounds through swipe gestures on a smartphone in a web app for the blind, it is great, I love it's simplicity! is there a way to also stop sounds, after they are triggered? Preferably with a fadeout?

**Comment by honkskillet** [comment]
@fgrond  While I too would love it LLA had some more features, you are posting on an unrelated issue that has already been closed.  Could you open a new issue?  Thanks.
